version: "3.2"
services:
  app:
    build: .
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3333:3333"
    environment:
      DB_CONNECTION: pg
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ${DB_NAME}
      NODE_ENV: development
      SESSION_DRIVER: cookie
      PORT: 3333
      HOST: 0.0.0.0
      ENV_SILENT: 'true'
    env_file: .env
    stdin_open: true
    tty: true
    command: node ace serve --watch
  db:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DB_NAME}
volumes:
  node_modules:
    external: true
