version: "3.2"
services:
  app:
    build: .
    volumes:
      - ./:/app
      - productcatalog_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: postgres
      NODE_ENV: development
      HOSTNAME: localhost
      ADMIN_EMAIL: test@test.com
      APP_KEY: supersecretsauce
    env_file: .env
    stdin_open: true
    tty: true
    command: yarn run dev
  db:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DB_NAME}
volumes:
  productcatalog_node_modules:
    external: true
