version: "3.2"
services:
  app:
    build: .
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      SESSION_DRIVER: cookie
      PORT: 3333
      HOST: 0.0.0.0
      ENV_SILENT: 'true'
    env_file: .env
    stdin_open: true
    tty: true
    command: node ace serve --watch
volumes:
  node_modules:
    external: true
