version: "3.2"
services:
  server:
    build: ./server
    volumes:
      - ./server:/app
      - productcatalog_server_node_modules:/app/node_modules
    ports:
      - "3333:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: postgres
      NODE_ENV: development
      HOSTNAME: localhost
      ADMIN_EMAIL: test@test.com
      APP_KEY: supersecretsauce
      API_TOKEN: supersecretspicysauce
    env_file: .env
    stdin_open: true
    tty: true
    command: yarn run dev
  db:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DB_NAME}
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - productcatalog_client_node_modules:/app/node_modules
    depends_on:
      - server
    environment:
      API_TOKEN: supersecretspicysauce
    command: yarn run start
volumes:
  productcatalog_server_node_modules:
    external: true
  productcatalog_client_node_modules:
    external: true
