name: Test all the things

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag productcatalog
    - name: Lint Typescript files
      run : docker run productcatalog:latest yarn run lint
