name: Test all the things

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build ./server --tag productcatalog
      - name: Lint Typescript files
        run: docker run productcatalog:latest yarn run lint

  test:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker-compose -f docker-compose.ci.yml build
      - name: Run server unit tests
        run: docker-compose -f docker-compose.ci.yml run server yarn run test:unit
      - name: Run client unit tests
        run: docker-compose -f docker-compose.ci.yml run client yarn run test --watchAll=false
      - name: Run server integration tests
        run: ./scripts/integration_tests.sh docker-compose.ci.yml
      - name: Run browser end to end tests
        run: ./scripts/browser_tests.sh docker-compose.ci.yml
